stages:
  - build
  - deploy
image: docker:20.10.5
services:
  - docker:20.10.5-dind
builder:
  stage: build
  script:
    - docker build -t hello:gitlab-$CI_COMMIT_SHORT_SHA .
  except:
    - main
deployer:
  stage: deploy
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        echo "Running on default branch '$CI_DEFAULT_BRANCH'"
        sudo docker login $CI_REGISTRY
        sudo docker build --pull -t  $CI_REGISTRY/tourk/dev-test/python-api:latest .
        sudo docker push $CI_REGISTRY/tourk/dev-test/python-api:latest
      else
        echo "Running on branch '$CI_COMMIT_BRANCH', will not be pushed"
      fi
  only:
    - main