apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-z1
  labels:
    app: dep_z1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dep_z1
  template:
    metadata:
      labels:
        app: dep_z1
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image_nginx }}:{{ .Values.tag_nginx }}
      - name: multitool
        image: {{ .Values.image_multitool }}:{{ .Values.tag_multitool }}
        env:
        - name: HTTP_PORT
          value: "8080"