apiVersion: v1
kind: Service
metadata:
  name: nginx-web-node
spec:
  selector:
    app: dep_z1
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
      nodePort: 30100
    - name: multitool
      protocol: TCP
      port: 9002
      targetPort: 8080
      nodePort: 30101
  type: NodePort