apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: watch-log
  namespace: default
subjects:
- kind: User
  name: tourk
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: homework-role
  apiGroup: rbac.authorization.k8s.io